### ISSUE TITLE
Unable to set fan speed to medium on 400S

### ISSUE THREAD

**Issue by angrycatmeowmeow** [RobertD502/home-assistant-iocare#17]
I have two Coway 400S units and control them with scripts in HA. At night I have them go from medium (67%) to low (33%), and when we go to bed they go from low to high (100%), then in the morning they are supposed to go back to medium, but they don't. It seems they aren't infinitely variable, you can only set the fan speeds to 33%, 67% or 100%, so that's what I have in my call service when I change the speeds. I don't see any errors in the logs or trace timeline.
![image](https://user-images.githubusercontent.com/67968528/206703852-bce0b6fb-4c1b-4c11-bbd5-59513d8b3928.png)
![image](https://user-images.githubusercontent.com/67968528/206703971-b0ab92df-d380-4bbe-b02c-facc7af2fb67.png)

**Comment by RobertD502** [comment]
Regarding speeds: A while back Home Assistant deprecated "low", "medium", and "high" speeds and required developers to convert preset speeds into percentages which is why only 33%, 67%, and 100% are available.

Regarding Purifiers not going to medium in the morning: I only have one suggestion. Instead of calling 67% for both purifiers in a single service call, have a service call to one setting it at 67% followed by a delay of a few seconds and then calling 67% for the other purifier. Coway's servers are a bit weird and sometimes don't acknowledge commands sent and without returning an error (I've had this happen even using their own app). I don't personally use HA automations and instead use Node Red - in this situation, within Node Red, I would send the commands (with delay) and check the state of the purifiers again (after a few seconds) to make sure they are reporting medium (67%). If not, then I'd have the Node Red automation call the service again until it sticks - not sure if you can recreate this in HA automations.

**Comment by angrycatmeowmeow** [comment]
Ok I messed with some more stuff and even though it shows 67% when the unit is manually set to level 2, if I want to set level 2 through HA I need to use 66% in the call service. I use NR, but in this instance NR only triggers the HA script based on time of day, presence etc. I'm currently running all of these purifier speed call services with no delay but I may add a 5 sec delay between purifier changes just to prevent any future issues. Thank you!
