### ISSUE TITLE
Coway authentication error

### ISSUE THREAD

**Issue by metril** [RobertD502/home-assistant-iocare#19]
Seems like the integration is failing to authenticate again. 

`Config entry 'Coway IoCare' for coway integration could not authenticate: Coway API authentication error: unable to retrieve auth code. Likely due to invalid username/password.`

My login information is correct because I can login to the phone app.

**Comment by RobertD502** [comment]
If you log in on the phone app you will be faced with a message telling you that it is time to change your password - it is part of their security since the migration. You can select either not now or in some number of days (don't recall exactly). I plan on sussing out the actual messaging to return a correct error code after the holidays.

**Comment by RobertD502** [comment]
Added option in `0.1.7` which allows users to ignore the password expired notice and skip changing their password.
