### ISSUE TITLE
Unable to authenticate to Coway API

### ISSUE THREAD

**Issue by npawelek** [RobertD502/home-assistant-iocare#45]
Bumping into an issue where I'm unable to authenticate to the Coway API. This doesn't appear limited to `0.4.2`, as I also noted the issue attempting to re-auth before updating from the prior version. I'm receiving the following error, which is also seen after removing and re-adding the integration.

```
2024-05-21 10:35:27.352 ERROR (MainThread) [custom_components.coway] Failed to get information from Coway servers: Coway API error while fetching login page: <coroutine object ClientResponse.text at 0x7f585b6651c0>
```
HA Core: `2024.5.4`

**Comment by RobertD502** [comment]
Took a bit of time, but I was able to figure out what was going on:

`Authentication`: They shut off the redirect URL that is used during authentication and, instead, now require the use of a different redirect URL. Switching over to that redirect URL fixed the authentication issue.

However, after getting things back up and running, I noticed that none of the control commands worked with Coway servers returning an error of `You were not logged in properly`. That led me down a rabbit hole attempting to figure out what else needed to be done with the access and refresh token we already have in order to be considered as having "logged in properly".

As is tradition with Coway's error messages commonly not pointing to the actual problem, I was logged in properly the entire time. I discovered that the issue was caused by them deprecating the purifier control endpoint and prefilter change frequency endpoint....NOTHING to do with not being properly logged in. After switching over to those new endpoints and rewriting the other parts of the requests that are now also completely different (data sent, headers, etc), everything is back up and running.

I've completed the required changes to the backend library. Next up, I will be making changes that are needed on the Home Assistant code side/adding some additional checks in the integration. Once that is done, there will be a new release.

Hope that gives some insight into what happened.

**Comment by RobertD502** [comment]
`0.4.3` has been released. Update to it and you should be back up and running again.

**Comment by tmcarr** [comment]
I installed the latest update a few hours ago, no dice. Still the same error as described above. 

I then made the mistake of removing the integration to try re-adding it, and now it wont connect at all.

**Comment by RobertD502** [comment]
> I installed the latest update a few hours ago, no dice. Still the same error as described above. 
> 
> 
> 
> I then made the mistake of removing the integration to try re-adding it, and now it wont connect at all. 

Can you post the error you are getting? Depending on what the error is, it'll clue me in to whether you are using the latest backend version or not.

**Comment by npawelek** [comment]
It seems to partially work for me. Authentication is functional, but all the devices are not reporting. My 400S seems to be okay, but the older 300S is reporting as offline with the following error:

```
2024-05-21 20:17:14.524 ERROR (MainThread) [custom_components.coway] Airmega 300S (Master) is reported as offline.
```

**Comment by RobertD502** [comment]
> It seems to partially work for me. Authentication is functional, but all the devices are not reporting. My 400S seems to be okay, but the older 300S is reporting as offline with the following error:
> 
> 
> 
> ```
> 
> 2024-05-21 20:17:14.524 ERROR (MainThread) [custom_components.coway] Airmega 300S (Master) is reported as offline.
> 
> ```

This message is logged when the Coway servers are reporting back that a purifier is "offline". When this happens, you have to manually get the purifier to report to the coway servers that it is online:

Even if the WiFi status light is normal on the purifier, you need to press and hold the WiFi button to turn WiFi off and then single-press it again to have the purifier connect to your WiFi, and, once the connection is reestablished, report to the Coway servers "hey, I'm actually online".

**Comment by npawelek** [comment]
Let me try that and report back. 

Also, thanks for the work here. All the changes on the server side has got be be annoying.

**Comment by RobertD502** [comment]
> Let me try that and report back. 
> 
> 
> 
> Also, thanks for the work here. All the changes on the server side has got be be annoying.

Very annoying! Their purifier control endpoint uses the key "comdVal" to specify the state of the command you're sending...the prefilter frequency change endpoint uses a "cmdVal" key (or maybe it is the other way around). Some of the states report back integers, but expect you to send the command as a string instead of an integer..the prefilter frequency endpoint has changed to now require it being an integer that is sent and not a string like before.

All of this is to say I have a feeling they aren't done breaking things. However, I'll try to keep up with the changes in a timely manner.

**Comment by tmcarr** [comment]
Welp, I went into HACS and forced it to "re-download" the addon, and then it all seemed to work properly. Sorry for the false alarm.

**Comment by npawelek** [comment]
That seemed to work, though it was already synced with wifi. Maybe it had to switch to a new endpoint or something. All working though. Thank you!

**Comment by RobertD502** [comment]
> That seemed to work, though it was already synced with wifi. Maybe it had to switch to a new endpoint or something. All working though. Thank you!

Not so much a new endpoint issue as it is a purifier reporting to Coway's servers issue - the purifiers don't use the same endpoints as the end users do when using the app/HA integration.  I've had this happen plenty of times in the past. I suspect the purifier fails to check in with their servers and so it gets listed as offline. The best I can do is to make users aware by logging a message. The mismatch in actual purifier state and what is reported by the servers can sometimes be seen when sending multiple commands back-to-back too fast via the integration. For example, let's say you sent a chain of commands rapidly and the last command was to power the purifier off. If the purifier failed to report to the Coway servers that it is off now, you may see that the purifier is listed as being on in the app (and this is the state the integration would show as well), but physically looking at the purifier you see that it is actually off.

They prevent this from happening when using the app by displaying a loading logo after a command is sent from the control page - this prevents the user from being able to send commands in rapid succession.

Just some quirks here and there. Anyways, I'm glad that the update worked for you!
